# Exported from Render on 2024-06-01T11:20:53Z
databases:
- name: pocket-server
  databaseName: pocket_server
  user: pocket_server_user
  plan: free
  region: ohio
  ipAllowList:
  - source: 98.243.189.45/32
    description: Jacob Feitler (jfeitler@gmail.com)
  - source: 0.0.0.0/0
    description: All
  postgresMajorVersion: "16"
services:
- type: web
  name: pocket-server
  runtime: node
  repo: https://github.com/jacob-af/pocket-server
  plan: starter
  envVars:
  - key: REFRESH_TOKEN_SECRET
    sync: false
  - key: LOCAL_URL
    sync: false
  - key: GOOGLE_SECRET
    sync: false
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: pocket-server
      property: connectionString
  - key: ACCESS_TOKEN_SECRET
    sync: false
  region: ohio
  buildCommand: pnpm install --frozen-lockfile; pnpm run build
  startCommand: pnpm run start:prod
  autoDeploy: false
version: "1"